In [77]:
import pandas as pd
import requests
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

df = pd.read_csv("C:/Users/chelego/Desktop/car_evaluation.csv", header = None) #if No Columns

df

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [79]:
df.columns = ["price", "maint", "doors", "persons", "lug_capacity", "safety", "output"]
df

price  maint  doors persons lug_capacity safety output
0     vhigh  vhigh      2       2        small    low  unacc
1     vhigh  vhigh      2       2        small    med  unacc
2     vhigh  vhigh      2       2        small   high  unacc
3     vhigh  vhigh      2       2          med    low  unacc
4     vhigh  vhigh      2       2          med    med  unacc
...     ...    ...    ...     ...          ...    ...    ...
1723    low    low  5more    more          med    med   good
1724    low    low  5more    more          med   high  vgood
1725    low    low  5more    more          big    low  unacc
1726    low    low  5more    more          big    med   good
1727    low    low  5more    more          big   high  vgood

[1728 rows x 7 columns]

In [81]:
df.isnull().sum()

price           0
maint           0
doors           0
persons         0
lug_capacity    0
safety          0
output          0
dtype: int64

In [83]:
label_encoders={}
for column in df.columns:
  if df[column].dtype == 'object':
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])
df

price  maint  doors  persons  lug_capacity  safety  output
0         3      3      0        0             2       1       2
1         3      3      0        0             2       2       2
2         3      3      0        0             2       0       2
3         3      3      0        0             1       1       2
4         3      3      0        0             1       2       2
...     ...    ...    ...      ...           ...     ...     ...
1723      1      1      3        2             1       2       1
1724      1      1      3        2             1       0       3
1725      1      1      3        2             0       1       2
1726      1      1      3        2             0       2       1
1727      1      1      3        2             0       0       3

[1728 rows x 7 columns]

In [87]:
import numpy as np

X = df.drop('output', axis=1).to_numpy()
y = df['output'].to_numpy()

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=42)

X_train.shape, X_test.shape, Y_train.shape, Y_test.shape


models = {
    "KNN": KNeighborsClassifier(n_neighbors=5), 
    "RF": RandomForestClassifier(n_estimators=100, random_state=42),
    "DT": DecisionTreeClassifier(random_state=42), 
    "RL": LogisticRegression(max_iter=2000), 
    "SVM": SVC()
}
from sklearn.metrics import confusion_matrix

for name, model in models.items():
    if name in ["KNN", "SVM"]:
        model.fit(X_train, Y_train)   
        Y_pred = model.predict(X_test)
    else:
        model.fit(X_train, Y_train)
        Y_pred = model.predict(X_test)

    accuracy = accuracy_score(Y_test, Y_pred)
    cm = confusion_matrix(Y_test, Y_pred)
    print("confusion_matrix:\n", cm)
    print(f"{name} 정확도: {accuracy:.4f}\n")

confusion_matrix:
 [[106   0   9   3]
 [ 11   8   0   0]
 [  4   0 354   0]
 [  6   0   2  16]]
KNN 정확도: 0.9326

confusion_matrix:
 [[109   7   1   1]
 [  1  17   0   1]
 [  3   0 355   0]
 [  3   0   0  21]]
RF 정확도: 0.9672

confusion_matrix:
 [[111   6   1   0]
 [  1  18   0   0]
 [  4   0 354   0]
 [  3   0   0  21]]
DT 정확도: 0.9711

confusion_matrix:
 [[ 20   0  92   6]
 [  3   0  16   0]
 [ 34   0 323   1]
 [ 12   0  11   1]]
RL 정확도: 0.6628

confusion_matrix:
 [[104   1  12   1]
 [ 14   3   0   2]
 [ 12   0 346   0]
 [  3   0   0  21]]
SVM 정확도: 0.9133

