In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


import pandas as pd
import requests
from io import StringIO
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix


url = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/main/heart.csv"

response = requests.get(url)

data = StringIO(response.text)
df = pd.read_csv(data)

In [20]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [22]:
df.columns = ["age","sex","cp","tresbps","chol","fbs","restecg","thalach","exang","oldpeak","shape","ca","thal","target"]
df

age  sex  cp  tresbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3      145   233    1        0      150      0      2.3   
1     37    1   2      130   250    0        1      187      0      3.5   
2     41    0   1      130   204    0        0      172      0      1.4   
3     56    1   1      120   236    0        1      178      0      0.8   
4     57    0   0      120   354    0        1      163      1      0.6   
..   ...  ...  ..      ...   ...  ...      ...      ...    ...      ...   
298   57    0   0      140   241    0        1      123      1      0.2   
299   45    1   3      110   264    0        1      132      0      1.2   
300   68    1   0      144   193    1        1      141      0      3.4   
301   57    1   0      130   131    0        1      115      1      1.2   
302   57    0   1      130   236    0        0      174      0      0.0   

     shape  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [24]:
label_encoders={}
for column in df.columns:
  if df[column].dtype == 'object':
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])
df

age  sex  cp  tresbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3      145   233    1        0      150      0      2.3   
1     37    1   2      130   250    0        1      187      0      3.5   
2     41    0   1      130   204    0        0      172      0      1.4   
3     56    1   1      120   236    0        1      178      0      0.8   
4     57    0   0      120   354    0        1      163      1      0.6   
..   ...  ...  ..      ...   ...  ...      ...      ...    ...      ...   
298   57    0   0      140   241    0        1      123      1      0.2   
299   45    1   3      110   264    0        1      132      0      1.2   
300   68    1   0      144   193    1        1      141      0      3.4   
301   57    1   0      130   131    0        1      115      1      1.2   
302   57    0   1      130   236    0        0      174      0      0.0   

     shape  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [26]:
import numpy as np

X = df.drop('target', axis=1).to_numpy()
y = df['target'].to_numpy()

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=42)

X_train.shape, X_test.shape, Y_train.shape, Y_test.shape


models = {
    "KNN": KNeighborsClassifier(n_neighbors=5), 
    "RF": RandomForestClassifier(n_estimators=100, random_state=42),
    "DT": DecisionTreeClassifier(random_state=42), 
    "RL": LogisticRegression(max_iter=2000), 
    "SVM": SVC()
}
from sklearn.metrics import confusion_matrix

for name, model in models.items():
    if name in ["KNN", "SVM"]:
        model.fit(X_train, Y_train)   
        Y_pred = model.predict(X_test)
    else:
        model.fit(X_train, Y_train)
        Y_pred = model.predict(X_test)

    accuracy = accuracy_score(Y_test, Y_pred)
    cm = confusion_matrix(Y_test, Y_pred)
    print("confusion_matrix:\n", cm)
    print(f"{name} 정확도: {accuracy:.4f}\n")

confusion_matrix:
 [[35  6]
 [ 5 45]]
KNN 정확도: 0.8791

confusion_matrix:
 [[33  8]
 [ 7 43]]
RF 정확도: 0.8352

confusion_matrix:
 [[32  9]
 [15 35]]
DT 정확도: 0.7363

confusion_matrix:
 [[32  9]
 [ 8 42]]
RL 정확도: 0.8132

confusion_matrix:
 [[32  9]
 [ 8 42]]
SVM 정확도: 0.8132

